Algoritmo "Ativ 01"
// Disciplina   : Introdução a Programação
// Professor   : Sônia Virginia Alves França
// Descrição   : Faça um algoritmo para ler dois números, somar estes números e apresentar o resultado
// na tela.
// Autor(a)    : Júlia
// Data atual  : 8/14/2024
Var
  numeroA, numeroB, soma : real



Inicio
 escreva("Digite o valor: ")
 leia(numeroA)
 escreva("Digite o valor: ")
 leia(numeroB)
 soma <- numeroA + numeroB
 escreva("Soma :", soma)

Fimalgoritmo